[package]
name = "grpc-client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.10.0", features = ["rt-multi-thread"] }
tonic = "0.5.2"
grpc = { path = "../grpc" }