version: '3.8'
services: 
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    environment:
    - ADDRESS=0.0.0.0
    - PORT=8083
    - JWT_SECRET_KEY=secret_key
    ports:
      - "8080:8080"

  search-microservice:
    build:
      context: ./search-microservice
      dockerfile: Dockerfile
    container_name: search-microservice
    restart: always
    depends_on:
      -  db
    volumes:
      - type: bind
        source: C:/Users/Home/Desktop/logovi/logs_search.log
        target: /search-microservice/logs/logs.log
    environment:
    - ADDRESS=0.0.0.0
    - PORT=8083
    - DATABASE_URL=postgres://postgres:zovemsejelenajelena@db/posts-db
    - LOG_STORAGE=/search-microservice/logs/logs.log
    ports:
      - "8083:8083"

  rating-microservice:
    build:
      context: ./rating-microservice
      dockerfile: Dockerfile
    container_name: rating-microservice
    restart: always
    depends_on:
      -  rating-db
    volumes:
      - type: bind
        source: C:/Users/Home/Desktop/logovi/logs_rating.log
        target: /rating-microservice/logs/logs.log
    environment:
    - ADDRESS=0.0.0.0
    - PORT=8084
    - DATABASE_URL=postgres://postgres:zovemsejelenajelena@rating-db/rating-db
    - LOG_STORAGE=/rating-microservice/logs/logs.log
    - JWT_SECRET_KEY=secret_key
    ports:
      - "8084:8084"

  posts-microservice:
    build:
      context: ./actix-example
      dockerfile: Dockerfile
    container_name: posts-microservice
    restart: always
    depends_on:
      -  db
    volumes:
      - type: bind
        source: C:/Users/Home/Desktop/logovi/logs_posts.log
        target: /actix-example/logs/logs.log
    environment:
    - ADDRESS=0.0.0.0
    - PORT=8082
    - DATABASE_URL=postgres://postgres:zovemsejelenajelena@db/posts-db
    - LOG_STORAGE=/actix-example/logs/logs.log
    - JWT_SECRET_KEY=secret_key
    ports:
      - "8082:8082"

  user-microservice:
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    container_name: user-microservice
    restart: always
    depends_on:
      -  users-db
    volumes:
      - type: bind
        source: C:/Users/Home/Desktop/logovi/logs_user.log
        target: /user-microservice/logs/logs.log
    environment:
    - ADDRESS=0.0.0.0
    - PORT=8081
    - DATABASE_URL=postgres://postgres:zovemsejelenajelena@users-db/users-db
    - LOG_STORAGE=/user-microservice/logs/logs.log
    - JWT_SECRET_KEY=secret_key
    ports:
      - "8081:8081"

  db:
    image: postgres:12.8-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: posts-db
      POSTGRES_PASSWORD: zovemsejelenajelena
    ports: 
      - "5432:5432"

  rating-db:
    image: postgres:12.8-alpine
    container_name: rating-db
    restart: always
    environment:
      POSTGRES_DB: rating-db
      POSTGRES_PASSWORD: zovemsejelenajelena
    ports: 
      - "5433:5433"

  users-db:
    image: postgres:12.8-alpine
    container_name: users-db
    restart: always
    environment:
      POSTGRES_DB: users-db
      POSTGRES_PASSWORD: zovemsejelenajelena
    ports: 
      - "5434:5434"
